### ISSUE TITLE
Allow user to delete certain clippings

### ISSUE THREAD

**Issue by mammuth** [mammuth/kindle-clippings#14]
It would be useful to delete certain clippings.

However, we cannot simply delete the clipping instances because they would be re-imported with the next clippings file upload.

Idea:
- Simple add a "deleted" flag to the clipping and exclude that in the default manager

Disadvantage: If the user deleted the clipping due to privacy concerns, that's some how an issue. But we could also erase the clippings data excluding the content_hash and then adapt the import process to don't import clippings when their hash already exists in the DB.

Ideas and contributions welcome!

Something to keep in mind:
- How to enable deletion of books?

**Comment by maelcum** [comment]
> However, we cannot simply delete the clipping instances because they would be re-imported with the next clippings file upload.
Well, that depends... If you flag the manually uploaded plaintext clippings, you would be able to delete those. But then.. if you have some logic for excluding individual Kindle clippings, why not use it for plaintext clippings as well.

> privacy concerns
That sounds as if the data is not encrypted today. Is that so? [Disclaimer: I can't read source code. Not a programmer.]

**Comment by mammuth** [comment]
Thanks, I'm super happy about security and privacy related questions!

> That sounds as if the data is not encrypted today. Is that so?

There is neither end-to-end-encryption in place nor server side encryption for the quotes.

Why? Server-Side encryption doesn't add any security in most threat models, e2ee is high effort and reduces the usability a lot (and features like email delivery could simple not work at all).

Side notes: 
- Passwords are salted and hashed, the connection to the database is encrypted and obviously your browser's requests are also running over https. 
- The app is hosted on the PaaS solution by Divio in case you want to read more about the infrastructure

But hey, the cool part about open source is, that everyone can take the code and deploy it to their own or trusted infrastructure if they want to do so, right? :wink:
