### ISSUE TITLE
Store each uploaded My Clippings.txt file

### ISSUE THREAD

**Issue by mammuth** [mammuth/kindle-clippings#16]
We should do this in order to be able to migrate features like #5 to already uploaded clippings.

At best, we create a model which keeps track of every upload with a date and the txt file (associated to a user).

**Comment by mammuth** [comment]
It will also help debugging issues due to different formats (like date formats on different Kindle devices etc.)

**Comment by mammuth** [comment]
If we do this we could also refactor the import process into more decoupled "jobs" where the upload only stores the file and following distinct jobs parse and store it in the DB, get a book cover via an external API, etc. ...

Obviously not needed, but might be a nice opportunity for cleaning the code up a bit 😊 
I think on the current hosting plan we even have Celery, so if we wanted we could actually run the jobs asynchronously (if not, there might still be value in separating the process)

**Comment by JSerwatka** [comment]
The idea with an async queue is great, but for this price it of course doesn't make any sense.

I believe that book cover fetching will be the most time costly element here, because to work properly it will probably need to use 2 requests (ISBN and book cover).

**Comment by JSerwatka** [comment]
I've created a mind map to try to gather all possible solutions to our problem with new features and storing the latest data. You can find it [here](https://miro.com/app/board/o9J_lTbzXDE=/). My favorite solution is marked in green. 

To compare clippings we have to use their hash, there is no other way here.

@mammuth, I'd love to hear your thoughts on that.

**Comment by mammuth** [comment]
> 've created a mind map to try to gather all possible solutions to our problem with new features and storing the latest data. You can find it here. My favorite solution is marked in green.

Sorry, I missed your miro board somehow, but I just reviewed it. To be honest, I'm not 100% sure what problem we're trying to solve with your green path.
Is it about the use case that the content of a clipping changes? 🤔 
> To compare clippings we have to use their hash, there is no other way here.

**Comment by mammuth** [comment]
> 've created a mind map to try to gather all possible solutions to our problem with new features and storing the latest data. You can find it here. My favorite solution is marked in green.

Sorry, I missed your miro board somehow, but I just reviewed it. To be honest, I'm not 100% sure what problem we're trying to solve with your green path.
Is it about the use case that the content of a clipping changes? 🤔 
Is this really a thing? For my reading workflow, it's not. I read books, make highlights, upload the highlights, and won't change the highlights afterward. I actually don't even know how this tool behaves, when adding comments, I think I never tried that 🙈 

> To compare clippings we have to use their hash, there is no other way here.

Random note: We already store the hash in the DB and use it as a DB unique constraint to ensure that we're not importing a clipping twice: 
https://github.com/mammuth/kindle-clippings/blob/aeedfd16dfece71b415defbd15a9c34fdd6652f6/clipping_manager/models/clipping.py#L67
