### ISSUE TITLE
small typo in /clipping_manager/templates/clipping_manager/dashboard.html

### ISSUE THREAD

**Issue by maelcum** [mammuth/kindle-clippings#18]
Hi.

There is a small typo (I assume) in `/clipping_manager/templates/clipping_manager/dashboard.html` and the live webpage `https://reading-notes.com/en/clippings/` as well:
"We can send you one of your quotes per e-mail every day or **_weekwever_** you like it!"
I'm not sure "weekwever" shouldn't rather be "however".  :)

Another small typo in the **_lower_** link behind the word "HERE" right after "Import your clippings".
The lower Link ends with two slashes '//' and thus does not resolve (or it does - but with "Not Found")

Nothing serious. Everything else works like a charm! Thank you! And have a nice day!

**Comment by mammuth** [comment]
Thanks for your contribution! :rocket: Nice catches.
