### ISSUE TITLE
New Navbar link

### ISSUE THREAD

**Issue by JSerwatka** [mammuth/kindle-clippings#30]
It'd be great to have an additional navbar link to go directly to the _clippings/browse/_ page. 
![image](https://user-images.githubusercontent.com/33938646/117495445-eac8e180-af75-11eb-9b90-c6f73f7f9a31.png)

I believe that you (@mammuth) have to do it yourself, as it requires CMS configuration.

**Comment by mammuth** [comment]
> I believe that you (@mammuth) have to do it yourself, as it requires CMS configuration.
Yes, the menu is currently using CMS pages only:
![image](https://user-images.githubusercontent.com/3121306/118109901-0c94ef00-b3e2-11eb-8037-f866ef4f14b0.png)

But we can add a CMS page that redirects to the route of the browse view 👍 

We actually already have stylings for a dropdown menu (although it's not beautiful), maybe we should use it?

![image](https://user-images.githubusercontent.com/3121306/118110201-68f80e80-b3e2-11eb-9660-c0f4ecef989e.png)

**Comment by mammuth** [comment]
I added a top-level menu item which is hidden for anonymized users: 
![image](https://user-images.githubusercontent.com/3121306/118110813-297df200-b3e3-11eb-8e3c-1de508a40d3b.png)

**Comment by JSerwatka** [comment]
nice!

**Comment by JSerwatka** [comment]
So this additional button can be named "Browse" and have child links like "Clippings", "Books", and maybe later "Tags"
