### ISSUE TITLE
Books page

### ISSUE THREAD

**Issue by JSerwatka** [mammuth/kindle-clippings#31]
### Description
I can add a page for displaying and searching for books in your library. 
Honestly, I have it already coded so I can show you what it looks like, and you can say what you think.

Views:
- Gallery view - each book is a separate card with a book cover, a title, and an author's name. Clicking on one of the books takes you to the book's clippings in _/browse_.
- List view - each book is a separate row in a table with a book cover, a title, an author, and a clippings count. On smaller screens, the author column is hidden. Clicking on one of the books takes you to the book's clippings in _/browse_.
- There is a button group that allows you to easily switch between the two views.

Search bar:
- Allows you to filter books by a book title and an author's name.
- Hides books that do not match the text of the search bar.

It looks like this:
- _Dashboard_
![image](https://user-images.githubusercontent.com/33938646/117974706-2c6adb00-b32e-11eb-8665-6a8ad933ce75.png)
- _Gallery view and search bar_
![image](https://user-images.githubusercontent.com/33938646/117975799-5b358100-b32f-11eb-9b1e-c4c915b1a12d.png)
Of course it is fully responsive:
![image](https://user-images.githubusercontent.com/33938646/117976074-a18ae000-b32f-11eb-9a87-16507423713e.png)
- _List view and search bar_
![image](https://user-images.githubusercontent.com/33938646/117976227-d1d27e80-b32f-11eb-91e1-174c13aa8382.png)
And on smaller screens:
![image](https://user-images.githubusercontent.com/33938646/117976272-e151c780-b32f-11eb-9945-a8a25e351ca5.png)

### Info
There can also be a dedicated link to this page like requested in #30. 

### TODOs
- [ ] An author is displayed as 'unknown' if it cannot be found in the database. At this point, it affects every book because it is not imported (issue mentioned in #5)
- [ ] Book covers are temporarily the same image. Future improvements require using some kind of API (maybe something from [here](https://github.com/public-apis/public-apis#books) and [this package](https://github.com/e-e-e/bookcovers)). After fetching all the covers using API, links to the covers should be stored in the db. There should also be an option to edit the cover's link.

**Comment by mammuth** [comment]
Love it! 

I'm also fine with integrating it before it's completely done/polished.

Btw, regarding the author, we could store the raw clipping files for introducing changes like this with backwards compatibility (see #16).

**Comment by JSerwatka** [comment]
Great!  :relaxed: 

> I'm also fine with integrating it before it's completely done/polished.

I think the same. I'll make a PR with this feature and move all the TODOs as seperate issues.

> Btw, regarding the author...

Sure thing, storing MyClipping will be essential when implementing note editing and clippings deleting features (prevents overwriting).

PS I'll be unavailable for about 2 weeks since tomorrow, so I'll get back to these issues when I'm back
