### ISSUE TITLE
Server Error at Random Quote on Page

### ISSUE THREAD

**Issue by balaji303** [mammuth/kindle-clippings#41]
I am getting Server Error (500) at my Random Quote on Page here is the default link -> https://reading-notes.com/en/clippings/random-fullscreen/?refresh=60

**Comment by mammuth** [comment]
Thanks for the report, @balaji303! 

This is the stacktrace:

<img width="1099" alt="Screenshot 2021-09-25 at 10 31 18" src="https://user-images.githubusercontent.com/3121306/134765074-c704e425-6c89-46a9-9a3a-09ae82fa581c.png">

@JSerwatka you wanna take a look?

**Comment by JSerwatka** [comment]
Sure, I look into it

**Comment by mammuth** [comment]
@Jserwatka's fix is deployed :+1:
