### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by balaji303** [mammuth/kindle-clippings#54]
![image](https://github.com/user-attachments/assets/fdfb1aec-b918-4910-bb10-c8ee2920e36e)

Just now I noticed the above error and reporting it with screenshot

**Comment by balaji303** [comment]
Site working fine as of now

**Comment by mammuth** [comment]
I guess it was a temporary hiccup. The screenshot also shows that you're not even connecting via TLS but the proxy should have redirected you to https://... :shrug:
